name: Release (Electron)

on:
  push:
    tags:
      - 'v*'   # runs when you push a tag like v1.0.0
  workflow_dispatch:

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm   # built-in dependency caching for npm/yarn/pnpm

      - name: Install dependencies
        run: npm ci

      - name: Build distributables
        run: npm run dist

      # Upload each OS build as a job artifact (handy for debugging too)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MirrorMirrorPharaoh-${{ matrix.os }}
          path: dist/**
          if-no-files-found: error
          retention-days: 14

  publish:
    # Create one release & attach all installers from the 3 OS jobs
    needs: [build-and-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
